{% set version = "11.0-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lahman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Lahman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Lahman/Lahman_{{ version }}.tar.gz
  sha256: 7ba1395469e92964ddbd59e3697d3205a0bd9ef10d37251cef9554397d9afd4b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
  run:
    - r-base
    - r-dplyr

test:
  commands:
    - $R -e "library('Lahman')"           # [not win]
    - "\"%R%\" -e \"library('Lahman')\""  # [win]

about:
  home: http://lahman.r-forge.r-project.org/
  license: GPL-2.0-or-later
  summary: Provides the tables from the 'Sean Lahman Baseball Database' as a set of R data.frames. It uses the data on pitching, hitting and fielding performance and other tables from 1871 through 2018, as recorded in the 2019 version of the database. Documentation examples show how many baseball questions can be investigated.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Lahman
# Type: Package
# Title: Sean 'Lahman' Baseball Database
# Version: 7.0-1
# Date: 2019-05-01
# Authors@R: c(person(given = "Michael", family = "Friendly", role="aut", email="friendly@yorku.ca"),  person(given ="Chris", family = "Dalzell", role=c("cre","aut"), email="cdalzell@gmail.com"), person(given ="Martin", family = "Monkman", role="aut"), person(given= "Dennis", family = "Murphy", role="aut"),  person(given ="Vanessa", family = "Foot", role="ctb"), person(given = "Justeena", family = "Zaki-Azat", role="ctb") )
# Author: Michael Friendly [aut], Chris Dalzell [cre, aut], Martin Monkman [aut], Dennis Murphy [aut], Vanessa Foot [ctb], Justeena Zaki-Azat [ctb]
# Maintainer: Chris Dalzell <cdalzell@gmail.com>
# Description: Provides the tables from the 'Sean Lahman Baseball Database' as a set of R data.frames. It uses the data on pitching, hitting and fielding performance and other tables from 1871 through 2018, as recorded in the 2019 version of the database. Documentation examples show how many baseball questions can be investigated.
# Depends: R (>= 2.10)
# Suggests: lattice, ggplot2, googleVis, data.table, vcd, reshape2, tidyr, zipcode, knitr, rmarkdown, car
# Imports: dplyr
# License: GPL
# URL: http://lahman.r-forge.r-project.org/
# LazyLoad: yes
# LazyData: yes
# BugReports: https://github.com/cdalzell/Lahman/issues
# Repository: CRAN
# Repository/R-Forge/Project: lahman
# Repository/R-Forge/Revision: 39
# Repository/R-Forge/DateTimeStamp: 2013-06-01 03:33:30
# Date/Publication: 2019-05-02 09:30:03 UTC
# Packaged: 2019-05-02 01:16:13 UTC; dz
# NeedsCompilation: no
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
