appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZAjcnuSCeycgtolWojzB5rVk1Hnp4FnCGTsixKcXzfbRVlpzeoVcpK9RcCuIelYpKyKBKu3DCU6TWv0u1w3BHIXNVqdxKiT29wIPNocv/ayOKX09Rn+xqBP+Ap1epA2lA4cKeK/vNtC4gsZrny67hcHRLv61fXgjLkxS6p5jZNM1tuCxbX2rOjEbhs2qTHLLgmwFXbXJqWnKsw7EJoLTsbj+F/QBD+AZorJNyXUAiYwE3YpDi+RSEahehgW4n9r0ndb+Hd5m+vRdBcwwGVdqFIwF7tlVfZGYvR6K6ulyRF+op4CT5Yo033dX/NFCgEAMv64WerqXQqW4gdJuE6Lr9BpXCzHvg943711vuYUkJ1SbJx17rpKrfz3cXcKzuv8Mlsw24nD/anVYJBx21cMN/tcBpezTVY4Ithvp3X0pxR/ymu6XX4rFLMnyTlbNMC6LKznEhrj+RyVL99SKe/Q4ByYpLVhqql+oywf2HfnEBLAGCKIa0XVJXMdFwBdihXtE7cBtjH3cAcXN4dOC/T9Fgv3owH6AWRhYLPyMqtu4QKpV5mEpKklK91JJz0WP79mMYcbDFLUaR2vorIuiwJjwuoR0Fei9PtM/8U6CBsDmbg+lfnZ6K62nwm245avzQoBUe4s9WN8Vv/e/D0rKwCGfYJwgq1Vxztieho01W2A9pzg=
conda_forge_output_validation: true
